Categories:
  - Sports & Health
License: GPL-3.0-or-later
AuthorName: Jeremey Tripp
SourceCode: https://github.com/jtripppiie/salmon-tracker
IssueTracker: https://github.com/jtripppiie/salmon-tracker/issues
Changelog: https://github.com/jtripppiie/salmon-tracker/releases

AutoName: Salmon Tracker

RepoType: git
Repo: https://github.com/jtripppiie/salmon-tracker.git

Builds:
  - versionName: 1.0.0
    versionCode: 3
    commit: v1.0.0
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.1
    versionCode: 4
    commit: v1.0.1
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.2
    versionCode: 5
    commit: v1.0.2
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.3
    versionCode: 6
    commit: v1.0.3
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.0.3
CurrentVersionCode: 6
